Add support for subscription and resource group level msi scopes
deislabs/cnab-azure-driver pull request #32
Opened 2021-06-08 11:05 UTC by jjcollinge

Addresses: #28

2021-06-15 11:23 UTC, simongdavies commented
/azp run

2021-06-16 09:14 UTC, simongdavies requested changes

2021-06-16 09:14 UTC, simongdavies commented on pkg/driver/aci-driver.go
> +	if _, err := guid.ParseString(subID); err != nil {
is there a reason that you cannot use [github.com/google/uuid](https://github.com/google/uuid/blob/512b657a42880af87e9f0d863aa6dccf3540d4ba/uuid.go) for this seen as this is already imported?

2021-06-16 09:38 UTC, jjcollinge commented on pkg/driver/aci-driver.go
> +	if _, err := guid.ParseString(subID); err != nil {
🤦‍♂️Good spot - I'm deep in the C# world atm and was looking for Guid parsing and completely forgot about uuid! It should be a drop in replacement so I'll update now.

2021-06-17 20:02 UTC, simongdavies approved these changes

2021-06-17 20:03 UTC, simongdavies commented
/azp run

2021-06-17 20:28 UTC, simongdavies commented
@jjcollinge can you sign your commit please?

2021-06-23 14:11 UTC, simongdavies requested changes
@jjcollinge  can you sign all the commits please? (or you can squash)

2021-06-23 14:41 UTC, simongdavies approved these changes

2021-06-23 14:57 UTC, jjcollinge commented
Sorry @simongdavies I missed the notification about your comment - I'm happy to sign the commits but I won't be able to until Friday if that works.

2021-07-02 16:18 UTC, jjcollinge commented
@simongdavies sorry about the delay I've rebased and signed the commits now - let me know if you need anything else.

2021-07-02 19:37 UTC, carolynvs commented
/azp run

2021-07-05 11:16 UTC, merged