Feature: allow for operating in alternative clouds
deislabs/cnab-azure-driver pull request #35
Opened 2021-06-22 12:33 UTC by AzurePlumber

Closes #34 

When operating outside of the public Azure cloud (i.e. in healthcare, finance, government, etc.) the default use of `https:\\management.azure.com` for the Azure Resource Manager and OAuth2 audience is problematic. This request implements a solution by introducing two more environment variables:

|  Environment Variable 	| Description  	|
|---	|---	|
| CNAB_AZURE_CLI_ARM_ENDPOINT        | The URL for the Azure Resource Manager when using from the CLI. This defaults to 'https://management.azure.com/' |
| CNAB_AZURE_MSI_AUDIENCE        | The 'audience' to include in the Cloud Shell MSI token request. This defaults to 'https://management.azure.com/' but can be changed if needed for clouds other than Azure public. |

Also, it appears possible to lookup the ARM Endpoint from the CLI. To keep this request as simple as possible, that step was not added.

2021-06-23 08:32 UTC, simongdavies commented
/azp run

2021-06-23 09:44 UTC, simongdavies requested changes

2021-06-23 09:44 UTC, simongdavies commented on pkg/azure/cloudshell.go
> +	}
Can you refactor this so this code is in a function and not repeated across this function and getOidFromToken?

2021-06-23 09:44 UTC, simongdavies commented on pkg/azure/login_info.go
> +	MSIAudience := os.Getenv("CNAB_AZURE_MSI_AUDIENCE")
I wonder if it is possible to default this by looking at the value of ACC_CLOUD if the user is running in cloudshell, that way there would be no need for a user to set the vars when running in cloudshell.

2021-06-23 09:44 UTC, simongdavies commented on pkg/driver/aci-driver.go
> +		ARMEndpoint := os.Getenv("CNAB_AZURE_CLI_ARM_ENDPOINT")
as with previous comment , can this be defaulted in cloudshell based on ACC_CLOUD?

2021-06-23 09:45 UTC, simongdavies commented
@AzurePlumber  . Thanks for the PR, please can you sign the CLA.

2021-06-23 14:08 UTC, carolynvs commented
@AzurePlumber Thanks for the pull request! I work at Microsoft and am the creator of Porter. I am trying to get a feel for who is using Porter, make sure that their use cases are covered, or are on our roadmap. I'd love to connect and hear about how you are using bundles. Email me at carolyn.vanslyck@microsoft.com if you are interested.

2021-06-23 16:19 UTC, AzurePlumber commented on pkg/azure/cloudshell.go
> +	}
Will do - left it simple, but agree this would be better DRY

2021-06-24 15:06 UTC, carolynvs commented
/azp run

2021-06-24 23:00 UTC, simongdavies approved these changes

2021-06-24 23:00 UTC, merged

2021-06-24 23:01 UTC, simongdavies commented
@AzurePlumber  I added a new issue for deriving the audience and ARM values when in cloudshell